"""Initial schema for code analysis

Revision ID: 001_initial_schema
Revises:
Create Date: 2024-12-01 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create repositories table
    op.create_table('repositories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('dominant_language', sa.String(length=50), nullable=False),
        sa.Column('last_analyzed', sa.DateTime(), nullable=True),
        sa.Column('analysis_status', sa.String(length=20), nullable=False),
        sa.Column('total_files', sa.Integer(), nullable=True, default=0),
        sa.Column('analyzed_files', sa.Integer(), nullable=True, default=0),
        sa.Column('total_lines', sa.Integer(), nullable=True, default=0),
        sa.Column('total_functions', sa.Integer(), nullable=True, default=0),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_repositories_url'), 'repositories', ['url'], unique=False)

    # Create linting_issues table
    op.create_table('linting_issues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repository_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('line_number', sa.Integer(), nullable=False),
        sa.Column('column_number', sa.Integer(), nullable=False),
        sa.Column('rule_id', sa.String(length=100), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('tool', sa.String(length=50), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('suggestion', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linting_issues_repository_id'), 'linting_issues', ['repository_id'], unique=False)
    op.create_index(op.f('ix_linting_issues_file_path'), 'linting_issues', ['file_path'], unique=False)
    op.create_index(op.f('ix_linting_issues_severity'), 'linting_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_linting_issues_tool'), 'linting_issues', ['tool'], unique=False)

    # Create quality_metrics table
    op.create_table('quality_metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repository_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('function_name', sa.String(length=255), nullable=True),
        sa.Column('cyclomatic_complexity', sa.Integer(), nullable=False),
        sa.Column('cognitive_complexity', sa.Integer(), nullable=True),
        sa.Column('halstead_volume', sa.Float(), nullable=True),
        sa.Column('halstead_difficulty', sa.Float(), nullable=True),
        sa.Column('maintainability_index', sa.Float(), nullable=True),
        sa.Column('technical_debt_ratio', sa.Float(), nullable=True),
        sa.Column('code_smells_count', sa.Integer(), nullable=True, default=0),
        sa.Column('duplicated_lines', sa.Integer(), nullable=True, default=0),
        sa.Column('lines_of_code', sa.Integer(), nullable=False),
        sa.Column('comment_lines', sa.Integer(), nullable=True, default=0),
        sa.Column('blank_lines', sa.Integer(), nullable=True, default=0),
        sa.Column('language', sa.String(length=50), nullable=False),
        sa.Column('analysis_date', sa.DateTime(), nullable=True),
        sa.Column('additional_metrics', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_metrics_repository_id'), 'quality_metrics', ['repository_id'], unique=False)
    op.create_index(op.f('ix_quality_metrics_file_path'), 'quality_metrics', ['file_path'], unique=False)
    op.create_index(op.f('ix_quality_metrics_cyclomatic_complexity'), 'quality_metrics', ['cyclomatic_complexity'], unique=False)
    op.create_index(op.f('ix_quality_metrics_maintainability_index'), 'quality_metrics', ['maintainability_index'], unique=False)

    # Create analysis_cache table
    op.create_table('analysis_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repository_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('analysis_type', sa.String(length=50), nullable=False),
        sa.Column('analysis_result', sa.JSON(), nullable=False),
        sa.Column('tool_version', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_cache_file_hash'), 'analysis_cache', ['file_hash'], unique=False)
    op.create_index(op.f('ix_analysis_cache_repository_id'), 'analysis_cache', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_cache_file_path'), 'analysis_cache', ['repository_id', 'file_path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_cache')
    op.drop_table('quality_metrics')
    op.drop_table('linting_issues')
    op.drop_table('repositories')
    # ### end Alembic commands ###